### ISSUE TITLE
Improve project groups

### ISSUE THREAD

**Issue by eanderson4** [anderson-optimization/frontend-documentation#166]
# Project Groups

These are in the projectGroup resource.  It is a general resource with an associated called `group`.  This houses a list of references to projects.  Here is an example of the `group` ref

```
{
  "<projectid>:{
    name: "<name>",
    rn: "<rn>",
    type: "<type>",
    wkt: "wkt",
  }
}
```
You can see an example of creating a ref for a group in the project detail page, where you can add a project to a group on your team.

## Associated issues

- [x] #165 - Remove projects from group
- [x] #162 - Add subGroup to group  
- [x] #163 - Add projects to group
- [x] #168 - Can't navigate to subGroups across teams

**Comment by eanderson4** [comment]
We will most likely do similar upgrades to asset groups after this.

**Comment by eanderson4** [comment]
There is a related issue where navigated to a subGroup doesn't respect cross team links

- [ ] #169
